package com.mimos.gov.my.sampleprocess.datamodel;

/**
 * This class was automatically generated by the data modeler tool.
 */

/**
 * This class was automatically generated by the data modeler tool.
 */


public class ApprovalDataObject implements java.io.Serializable
{


   static final long serialVersionUID = 1L;


   private java.lang.String approverName;
   private java.lang.Boolean approved;
   private java.lang.String rejectReason;
   private java.lang.String requesterName;
   private java.lang.String requesterNote;


   private java.lang.String approverNote;


   private java.lang.Double amount;


   private java.lang.String requesterDept;


   private java.lang.Short requesterJoinLen;


   private java.lang.String approvalPath;


   private java.lang.String approvalDept;


   public ApprovalDataObject()
   {
   }


   public java.lang.String getApproverName()
   {
      return this.approverName;
   }


   public void setApproverName(java.lang.String approverName)
   {
      this.approverName = approverName;
   }


   public java.lang.Boolean getApproved()
   {
      return this.approved;
   }


   public void setApproved(java.lang.Boolean approved)
   {
      this.approved = approved;
   }


   public java.lang.String getRejectReason()
   {
      return this.rejectReason;
   }


   public void setRejectReason(java.lang.String rejectReason)
   {
      this.rejectReason = rejectReason;
   }


   public java.lang.String getRequesterName()
   {
      return this.requesterName;
   }


   public void setRequesterName(java.lang.String requesterName)
   {
      this.requesterName = requesterName;
   }


   public java.lang.String getRequesterNote()
   {
      return this.requesterNote;
   }


   public void setRequesterNote(java.lang.String requesterNote)
   {
      this.requesterNote = requesterNote;
   }


   public java.lang.String getApproverNote()
   {
      return this.approverNote;
   }


   public void setApproverNote(java.lang.String approverNote)
   {
      this.approverNote = approverNote;
   }


   public java.lang.Double getAmount()
   {
      System.out.println("in getAmount:" + this.amount);
      return this.amount;
   }


   public void setAmount(java.lang.Double amount)
   {
      this.amount = amount;
   }


   public java.lang.String getRequesterDept()
   {
      System.out.println("in getRequesterDept:" + this.requesterDept);
      return this.requesterDept;
   }


   public void setRequesterDept(java.lang.String requesterDept)
   {
      this.requesterDept = requesterDept;
   }


   public java.lang.Short getRequesterJoinLen()
   {
      System.out.println("in getRequesterJoinLen:" + this.requesterJoinLen);
      return this.requesterJoinLen;
   }


   public void setRequesterJoinLen(java.lang.Short requesterJoinLen)
   {
      this.requesterJoinLen = requesterJoinLen;
   }


   public java.lang.String getApprovalPath()
   {
      return this.approvalPath;
   }


   public void setApprovalPath(java.lang.String approvalPath)
   {
      System.out.println("Setting approval Path : " + approvalPath);
      this.approvalPath = approvalPath;
   }


   public java.lang.String getApprovalDept()
   {
      return this.approvalDept;
   }


   public void setApprovalDept(java.lang.String approvalDept)
   {
      this.approvalDept = approvalDept;
   }


   public ApprovalDataObject(java.lang.String approverName,
         java.lang.Boolean approved, java.lang.String rejectReason,
         java.lang.String requesterName, java.lang.String requesterNote,
         java.lang.String approverNote, java.lang.Double amount,
         java.lang.String requesterDept, java.lang.Short requesterJoinLen,
         java.lang.String approvalPath, java.lang.String approvalDept)
   {
      this.approverName = approverName;
      this.approved = approved;
      this.rejectReason = rejectReason;
      this.requesterName = requesterName;
      this.requesterNote = requesterNote;
      this.approverNote = approverNote;
      this.amount = amount;
      this.requesterDept = requesterDept;
      this.requesterJoinLen = requesterJoinLen;
      this.approvalPath = approvalPath;
      this.approvalDept = approvalDept;
   }
}