package com.mimos.gov.my.sampleprocess.datamodel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApprovalDataObject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ApprovalDataObject() {
    }

}